import type { QuestionRecord, CompetencyKey, PathwayId } from './types';

// ── Variant Libraries ─────────────────────────────────────────────────────────
export const V = {
  aircraft: ['Boeing 777', 'Airbus A350', 'Airbus A380', 'Dash 8-400', 'Cessna 172', 'Bell 412 helicopter', 'DJI Matrice UAV', 'Beechcraft King Air'],
  direction: ['north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest'],
  angle: ['45°', '90°', '135°', '180°', '270°'],
  turn: ['left', 'right'],
  gate: ['Gate 12', 'Gate 21', 'Gate 33', 'Gate 42', 'Gate 7', 'Gate 18'],
  runway: ['Runway 08', 'Runway 17', 'Runway 26', 'Runway 35', 'Runway 04'],
  time: ['14:35', '16:25', '08:10', '21:45', '11:55', '19:20'],
  weather: ['light rain', 'clear', 'overcast', 'scattered cloud', 'light snow', 'morning fog'],
  role: ['AME', 'First Officer', 'Airport Operations Officer', 'Aircraft Assembler', 'Avionics Technician'],
  institution: ['BCIT', 'SAIT', 'Canadore College', 'Mount Royal University'],
  partNumber: ['A35-1178-04', 'B77-2291-17', 'C14-0034-88', 'D22-5571-03'],
  tolerance: ['125 mm ± 1 mm', '48.5 mm ± 0.5 mm', '200 mm ± 2 mm'],
};

function pick(arr: string[]): string {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function applyVariants(template: string, vars?: Record<string, string[]>): string {
  if (!vars) return template;
  let result = template;
  for (const [key, options] of Object.entries(vars)) {
    result = result.replaceAll(`[${key}]`, pick(options));
  }
  return result;
}

// ── Question Bank ─────────────────────────────────────────────────────────────
export const QUESTION_BANK: QuestionRecord[] = [

  // ── BANK 01: Aviation Discovery ───────────────────────────────────────────
  {
    questionId: 'DISC-001',
    family: 'Aviation Discovery',
    familyCode: '01',
    primaryCompetency: 'AL',
    secondaryCompetencies: [],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "What first sparked your interest in aviation or aerospace?",
    evidenceRubric: [
      { indicator: 'genuine_engagement', label: 'Genuine Engagement', description: 'Participant describes a specific memory, person, or moment', competency: 'AL', positive: true },
      { indicator: 'reflective_depth', label: 'Reflective Depth', description: 'Goes beyond surface answer to explain what resonated', competency: 'AL', positive: true },
    ],
    designNote: "Optional follow-up: What about that experience caught your attention?",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'DISC-002',
    family: 'Aviation Discovery',
    familyCode: '01',
    primaryCompetency: 'SA',
    secondaryCompetencies: ['AL'],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "Imagine you're watching aircraft operations at a busy airport. What are you naturally most curious about?",
    evidenceRubric: [
      { indicator: 'observational_focus', label: 'Observational Focus', description: 'Identifies specific operational details rather than generic responses', competency: 'SA', positive: true },
      { indicator: 'technical_curiosity', label: 'Technical Curiosity', description: 'Shows interest in how things work', competency: 'AL', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'DISC-003',
    family: 'Aviation Discovery',
    familyCode: '01',
    primaryCompetency: 'AL',
    secondaryCompetencies: [],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "If you could spend one day alongside any aviation professional, who would you choose and what would you want to learn?",
    evidenceRubric: [
      { indicator: 'career_awareness', label: 'Career Awareness', description: 'Shows awareness of different aviation roles', competency: 'AL', positive: true },
      { indicator: 'learning_intent', label: 'Learning Intent', description: 'Articulates what they would learn, not just who they would meet', competency: 'AL', positive: true },
    ],
    designNote: "Do not treat selected occupation as the recommended career.",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'DISC-004',
    family: 'Aviation Discovery',
    familyCode: '01',
    primaryCompetency: 'DM',
    secondaryCompetencies: ['AL'],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "Imagine three opportunities: working directly with an aircraft, coordinating aircraft movements, or analyzing information to support operations. Which would you explore first, and why?",
    variantVariables: {},
    evidenceRubric: [
      { indicator: 'reasoning_given', label: 'Reasoning Provided', description: 'Explains why, not just which one', competency: 'DM', positive: true },
      { indicator: 'self_awareness', label: 'Self-Awareness', description: 'Shows understanding of their own strengths or preferences', competency: 'AL', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'DISC-005',
    family: 'Aviation Discovery',
    familyCode: '01',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['PS'],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "When you encounter something technical you've never seen before, what do you usually do first?",
    evidenceRubric: [
      { indicator: 'structured_approach', label: 'Structured Approach', description: 'Describes a systematic method (research, ask, observe)', competency: 'AL', positive: true },
      { indicator: 'perseverance', label: 'Perseverance', description: 'Shows willingness to work through unfamiliar problems', competency: 'PS', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 02: Spatial Intelligence ─────────────────────────────────────────
  {
    questionId: 'SPAT-001',
    family: 'Spatial Intelligence',
    familyCode: '02',
    primaryCompetency: 'SR',
    secondaryCompetencies: [],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A [AIRCRAFT] is facing [DIR1]. It turns [ANGLE1] [TURN1] and then [ANGLE2] [TURN2]. Which direction is it now facing?",
    variantVariables: {
      AIRCRAFT: V.aircraft,
      DIR1: ['north', 'south', 'east', 'west'],
      ANGLE1: ['90°', '180°'],
      TURN1: V.turn,
      ANGLE2: ['90°', '180°'],
      TURN2: V.turn,
    },
    evidenceRubric: [
      { indicator: 'correct_orientation', label: 'Correct Final Orientation', description: 'Arrives at correct answer', competency: 'SR', positive: true },
      { indicator: 'shows_reasoning', label: 'Shows Reasoning', description: 'Explains turn sequence step by step', competency: 'SR', positive: true },
      { indicator: 'systematic_working', label: 'Systematic Working', description: 'Works through each turn in order', competency: 'PS', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SPAT-002',
    family: 'Spatial Intelligence',
    familyCode: '02',
    primaryCompetency: 'SR',
    secondaryCompetencies: ['WM'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "An [AIRCRAFT] is facing [DIR1]. It turns [ANGLE1], then [ANGLE2] [TURN1], followed by another [ANGLE3] [TURN2]. What is its final direction?",
    variantVariables: {
      AIRCRAFT: V.aircraft,
      DIR1: ['north', 'south', 'east', 'west'],
      ANGLE1: ['180°'],
      ANGLE2: ['90°'],
      TURN1: V.turn,
      ANGLE3: ['90°'],
      TURN2: V.turn,
    },
    evidenceRubric: [
      { indicator: 'multi_step_tracking', label: 'Multi-Step Tracking', description: 'Tracks three sequential turns correctly', competency: 'SR', positive: true },
      { indicator: 'working_memory_use', label: 'Working Memory', description: 'Maintains intermediate orientations through sequence', competency: 'WM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SPAT-003',
    family: 'Spatial Intelligence',
    familyCode: '02',
    primaryCompetency: 'SR',
    secondaryCompetencies: ['AP'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "You are looking at the top view of a [AIRCRAFT] component. If you flip it 180° along its horizontal axis, describe what you would now see — specifically whether any markings that were on the top-left would move.",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'correct_flip_reasoning', label: 'Correct Flip Reasoning', description: 'Correctly identifies the top becomes the bottom and left/right orientation', competency: 'SR', positive: true },
      { indicator: 'describes_movement', label: 'Describes Movement', description: 'Traces a specific marking or feature through the flip', competency: 'SR', positive: true },
      { indicator: 'systematic_approach', label: 'Systematic Approach', description: 'Works through the transformation step by step', competency: 'AP', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SPAT-004',
    family: 'Spatial Intelligence',
    familyCode: '02',
    primaryCompetency: 'SR',
    secondaryCompetencies: ['MR'],
    careerContext: ['assembler', 'structural_repair', 'ame', 'amt'],
    difficulty: 3,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A flat sheet of material is folded along its centre line so that the left half lies on top of the right half. A hole is then punched through both layers at the top-left corner of the folded sheet. When the sheet is fully unfolded, how many holes are there, and where are they located?",
    evidenceRubric: [
      { indicator: 'correct_hole_count', label: 'Correct Hole Count', description: 'Identifies two holes when unfolded', competency: 'SR', positive: true },
      { indicator: 'mirror_position', label: 'Mirror Position', description: 'Correctly places the second hole as a mirror of the first', competency: 'SR', positive: true },
      { indicator: 'explains_reasoning', label: 'Explains Reasoning', description: 'Describes the fold-and-punch logic step by step', competency: 'MR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SPAT-005',
    family: 'Spatial Intelligence',
    familyCode: '02',
    primaryCompetency: 'SR',
    secondaryCompetencies: ['PS'],
    careerContext: ['pilot', 'ame', 'amt', 'ground_ops', 'airport_ops'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are taxiing a [AIRCRAFT] on the apron. Starting at Bay 1, you need to reach Bay 4 without crossing the restricted zone between Bays 2 and 3. Describe the route you would take and the turns involved.",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'spatial_planning', label: 'Spatial Planning', description: 'Plans a route around a restriction', competency: 'SR', positive: true },
      { indicator: 'constraint_awareness', label: 'Constraint Awareness', description: 'Acknowledges and respects the restricted zone', competency: 'SO', positive: true },
      { indicator: 'logical_sequence', label: 'Logical Sequence', description: 'Describes movement in logical order', competency: 'PS', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 03: Mechanical Intelligence ──────────────────────────────────────
  {
    questionId: 'MECH-001',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: [],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 1,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Two technicians use different-length handles on identical fasteners and apply the same force. Which produces the greater turning effect, and why?",
    evidenceRubric: [
      { indicator: 'correct_mechanical_reasoning', label: 'Correct Reasoning', description: 'Identifies longer handle produces greater turning effect', competency: 'MR', positive: true },
      { indicator: 'explains_why', label: 'Explains Why', description: 'References distance/leverage relationship (even without using the word torque)', competency: 'MR', positive: true },
      { indicator: 'applies_principle', label: 'Applies Principle', description: 'Could generalize the concept to another situation', competency: 'PS', positive: true },
    ],
    designNote: "Do not require the participant to know the term torque.",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-002',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: ['SR'],
    careerContext: ['ame', 'amt', 'assembler', 'avionics'],
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Gear A rotates clockwise and meshes directly with Gear B. Gear B meshes with Gear C. Which direction will Gear C rotate, and how did you work it out?",
    evidenceRubric: [
      { indicator: 'gear_direction_correct', label: 'Correct Direction', description: 'Correctly identifies Gear C rotates clockwise', competency: 'MR', positive: true },
      { indicator: 'sequential_reasoning', label: 'Sequential Reasoning', description: 'Traces A→B→C direction changes step by step', competency: 'MR', positive: true },
      { indicator: 'visualization', label: 'Spatial Visualization', description: 'Appears to mentally rotate/visualize the system', competency: 'SR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-003',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: ['PS'],
    careerContext: ['ame', 'amt', 'assembler', 'avionics'],
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A pulley system uses two wheels of different sizes connected by a belt. The small wheel drives the large wheel. If the small wheel completes 4 full rotations, how many rotations does the large wheel complete — and what principle explains that?",
    evidenceRubric: [
      { indicator: 'fewer_rotations', label: 'Fewer Rotations', description: 'Correctly identifies the large wheel rotates fewer times', competency: 'MR', positive: true },
      { indicator: 'speed_ratio_reasoning', label: 'Speed Ratio Reasoning', description: 'References size/speed trade-off (circumference or mechanical advantage)', competency: 'MR', positive: true },
      { indicator: 'generalizes_principle', label: 'Generalizes Principle', description: 'Could apply the same reasoning to gears or other drive systems', competency: 'PS', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-004',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: ['SO'],
    careerContext: ['ame', 'amt', 'assembler'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are hand-tightening a fastener and notice it turns much more easily than expected for the last few rotations. What might this indicate, and what would you do?",
    evidenceRubric: [
      { indicator: 'cross_thread_or_strip', label: 'Identifies Risk', description: 'Considers cross-threading, stripped threads, or wrong fastener', competency: 'MR', positive: true },
      { indicator: 'stops_tightening', label: 'Stops Tightening', description: 'Does not continue tightening — stops and investigates', competency: 'SO', positive: true },
      { indicator: 'removes_and_inspects', label: 'Removes and Inspects', description: 'Backs out the fastener to inspect threads', competency: 'MR', positive: true },
      { indicator: 'does_not_apply_torque', label: 'Does Not Apply Torque', description: 'Does not proceed to torque application while issue is unresolved', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-005',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: ['AP', 'PS'],
    careerContext: ['ame', 'amt', 'avionics', 'assembler'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "An aircraft system relies on fluid pressure to operate a control surface. The pressure gauge reads normal, but the control surface responds more slowly than expected. Where would you begin your investigation, and why?",
    evidenceRubric: [
      { indicator: 'systematic_isolation', label: 'Systematic Isolation', description: 'Proposes checking between the pressure source and the actuator', competency: 'PS', positive: true },
      { indicator: 'identifies_restriction_or_leak', label: 'Identifies Restriction or Leak', description: 'Considers a partial restriction, internal leak, or actuator fault', competency: 'MR', positive: true },
      { indicator: 'distinguishes_pressure_from_flow', label: 'Distinguishes Pressure from Flow', description: 'Recognizes normal pressure does not guarantee adequate flow', competency: 'AP', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-006',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: ['AP', 'SO', 'PR'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "Two fasteners look nearly identical but have different part numbers and specifications. What information would you verify before deciding they are interchangeable?",
    evidenceRubric: [
      { indicator: 'documentation_check', label: 'Documentation Check', description: 'References approved parts list, IPC, or CMM', competency: 'PR', positive: true },
      { indicator: 'material_specification', label: 'Specification Check', description: 'Mentions dimensions, material, grade, or coating', competency: 'AP', positive: true },
      { indicator: 'not_by_appearance', label: 'Not Appearance Alone', description: 'Does not rely solely on visual similarity', competency: 'SO', positive: true },
      { indicator: 'authority_verification', label: 'Authority Verification', description: 'Involves engineering or approved technical authority', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-007',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'MR',
    secondaryCompetencies: ['PS'],
    careerContext: ['ame', 'amt', 'avionics', 'assembler'],
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Component A drives Component B, and Component B drives Component C. If Component B suddenly stops moving, what would you expect to happen to Component C, and what might that tell you about Component B?",
    evidenceRubric: [
      { indicator: 'failure_chain_reasoning', label: 'Failure Chain Reasoning', description: 'Correctly identifies C stops when B fails', competency: 'MR', positive: true },
      { indicator: 'root_cause_thinking', label: 'Root Cause Thinking', description: 'Considers what might cause B to fail', competency: 'PS', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MECH-008',
    family: 'Mechanical Intelligence',
    familyCode: '03',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['MR', 'PR'],
    careerContext: ['ame', 'amt', 'assembler'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You're preparing to use a power tool for a precision aircraft assembly task. What would you verify before starting?",
    evidenceRubric: [
      { indicator: 'tool_serviceability', label: 'Tool Serviceability', description: 'Checks tool is calibrated, serviceable, and appropriate for task', competency: 'SO', positive: true },
      { indicator: 'procedure_check', label: 'Procedure Review', description: 'Reviews the work order or procedure before starting', competency: 'PR', positive: true },
      { indicator: 'safety_precautions', label: 'Safety Precautions', description: 'Identifies PPE or worksite safety requirements', competency: 'SO', positive: true },
      { indicator: 'not_brand_focus', label: 'Non-Brand Focus', description: 'Does not focus on brand/model preference', competency: 'MR', positive: false },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 04: Blueprint & Technical Intelligence ───────────────────────────
  {
    questionId: 'BLUE-001',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['MR'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 1,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A technical drawing shows a component with three views: front, top, and side. The front view shows a rectangle with a circle in the centre. What does the circle most likely represent in three dimensions, and how would you confirm your interpretation using the other views?",
    evidenceRubric: [
      { indicator: 'identifies_hole_or_cylinder', label: 'Identifies Hole or Cylinder', description: 'Recognizes the circle likely represents a hole or cylindrical feature', competency: 'MR', positive: true },
      { indicator: 'uses_multiple_views', label: 'Uses Multiple Views', description: 'Looks to the top or side view to confirm the feature', competency: 'AP', positive: true },
      { indicator: 'does_not_guess_from_one_view', label: 'Does Not Guess From One View', description: 'Does not commit to an interpretation without cross-referencing views', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'BLUE-002',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['PS'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A drawing specifies [TOLERANCE]. Four components measure [MEASURE1], [MEASURE2], [MEASURE3] and [MEASURE4]. Which component is outside the stated tolerance, and how did you determine that?",
    variantGenerator: 'tolerance_outlier',
    evidenceRubric: [
      { indicator: 'correct_identification', label: 'Correct Identification', description: 'Identifies the out-of-tolerance component', competency: 'AP', positive: true },
      { indicator: 'tolerance_method', label: 'Tolerance Method', description: 'Explains how they calculated or compared the tolerance', competency: 'AP', positive: true },
      { indicator: 'precision_mindset', label: 'Precision Mindset', description: 'Shows understanding of why tolerance matters', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'BLUE-003',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['SR'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A drawing uses dashed lines to show features inside a component. What do dashed lines typically represent on a technical drawing, and why is it important to understand them before fabricating a part?",
    evidenceRubric: [
      { indicator: 'hidden_lines_identified', label: 'Hidden Lines Identified', description: 'Correctly identifies dashed lines as hidden features', competency: 'AP', positive: true },
      { indicator: 'explains_significance', label: 'Explains Significance', description: 'Explains that fabricating without understanding hidden features could cause errors', competency: 'SO', positive: true },
      { indicator: 'references_internal_features', label: 'References Internal Features', description: 'Mentions bores, slots, internal passages, or pockets', competency: 'SR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'BLUE-004',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['PR', 'MR'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A drawing calls for a surface finish of Ra 1.6. The component you've received has a visibly rough surface. Without a measuring instrument available, what steps would you take?",
    evidenceRubric: [
      { indicator: 'does_not_accept_on_appearance', label: 'Does Not Accept on Appearance', description: 'Does not approve the component based on visual inspection alone', competency: 'AP', positive: true },
      { indicator: 'seeks_measurement', label: 'Seeks Measurement', description: 'Identifies need for a profilometer or equivalent instrument', competency: 'PR', positive: true },
      { indicator: 'holds_for_inspection', label: 'Holds for Inspection', description: 'Does not install the component until conformance is confirmed', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'BLUE-005',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['PS'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair', 'avionics'],
    difficulty: 3,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A drawing has two revision entries. Revision A changes the material specification. Revision B changes a hole diameter and references a note that has itself been superseded. How do you determine what the current requirements are for this part?",
    evidenceRubric: [
      { indicator: 'reads_full_revision_history', label: 'Reads Full Revision History', description: 'Does not assume the latest change is the only relevant one', competency: 'AP', positive: true },
      { indicator: 'resolves_superseded_note', label: 'Resolves Superseded Note', description: 'Identifies the need to find the current version of the referenced note', competency: 'PS', positive: true },
      { indicator: 'controlled_document_check', label: 'Controlled Document Check', description: 'Confirms the drawing itself is the current approved revision', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'BLUE-006',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['MR', 'SO'],
    careerContext: ['assembler', 'structural_repair', 'ame', 'amt'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A drawing specifies [TOLERANCE] for a critical fastener hole. You measure the hole at [MEASURE1] on one side and [MEASURE2] on the opposite side of the same hole. What does this tell you, and what would you do?",
    variantGenerator: 'out_of_round_hole',
    evidenceRubric: [
      { indicator: 'identifies_out_of_round', label: 'Identifies Out-of-Round', description: 'Recognizes the hole is not circular — diameter varies across measurements', competency: 'AP', positive: true },
      { indicator: 'non_conformance', label: 'Flags Non-Conformance', description: 'Correctly identifies at least one measurement is outside tolerance', competency: 'MR', positive: true },
      { indicator: 'does_not_install', label: 'Does Not Install', description: 'Does not proceed with installation until the issue is resolved', competency: 'SO', positive: true },
      { indicator: 'documents_and_reports', label: 'Documents and Reports', description: 'Raises a non-conformance report or involves QA', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'BLUE-007',
    family: 'Blueprint & Technical Intelligence',
    familyCode: '04',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['PR', 'DM'],
    careerContext: ['ame', 'amt', 'assembler', 'structural_repair'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You have a technical drawing for a component you need to fabricate, but one critical dimension is missing and the drawing has no revision block. Would you begin fabrication? Explain your decision.",
    evidenceRubric: [
      { indicator: 'stops_before_proceeding', label: 'Stops Before Proceeding', description: 'Does not begin fabrication without complete information', competency: 'SO', positive: true },
      { indicator: 'seeks_controlled_data', label: 'Seeks Controlled Data', description: 'Identifies need for current, approved technical documentation', competency: 'PR', positive: true },
      { indicator: 'escalation', label: 'Escalation', description: 'Involves engineering or technical authority', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 05: Attention & Precision ────────────────────────────────────────
  {
    questionId: 'PREC-001',
    family: 'Attention & Precision',
    familyCode: '05',
    primaryCompetency: 'AP',
    secondaryCompetencies: [],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Read the following sequence carefully and identify which number is repeated:\n\n4719, 3826, 5041, 4719, 6253, 7814, 3092, 5041\n\nHow many duplicates are there, and which positions do they appear in?",
    evidenceRubric: [
      { indicator: 'identifies_both_duplicates', label: 'Identifies Both Duplicates', description: 'Finds both 4719 (positions 1 and 4) and 5041 (positions 3 and 8)', competency: 'AP', positive: true },
      { indicator: 'correct_positions', label: 'Correct Positions', description: 'Accurately states the positions of each duplicate', competency: 'AP', positive: true },
      { indicator: 'systematic_scan', label: 'Systematic Scan', description: 'Describes checking each number against the others', competency: 'PS', positive: true },
    ],
    repeatProtection: false,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PREC-002',
    family: 'Attention & Precision',
    familyCode: '05',
    primaryCompetency: 'AP',
    secondaryCompetencies: [],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "From the following list, select the entry that exactly matches part number [PART]:\n\nA) [PARTA]\nB) [PARTB]\nC) [PARTC]\nD) [PARTD]",
    variantVariables: {
      PART: ['A35-1178-04', 'B77-2291-17'],
      PARTA: ['A35-1178-04'],
      PARTB: ['A35-1178-40'],
      PARTC: ['A35-1178-04'],
      PARTD: ['A53-1178-04'],
    },
    evidenceRubric: [
      { indicator: 'accurate_match', label: 'Accurate Match', description: 'Selects the correct exact match', competency: 'AP', positive: true },
      { indicator: 'identifies_distractors', label: 'Identifies Distractors', description: 'Notices subtle differences in near-identical options', competency: 'AP', positive: true },
    ],
    repeatProtection: false,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PREC-003',
    family: 'Attention & Precision',
    familyCode: '05',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['WM'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Below are two maintenance log entries. Identify every difference between them — including spacing, punctuation, and capitalization:\n\nEntry A: Aircraft C-GABC, Work Order 2241-B, Task 14.3 — Hydraulic filter replaced. Sign-off: J. Marsh, AME-M, Lic. 4471.\n\nEntry B: Aircraft C-GABC, Work Order 2241-B, Task 14.3 — Hydraulic filter replaced. Sign-off: J. Marsh AME-M, Lic. 4471.",
    evidenceRubric: [
      { indicator: 'spots_missing_comma', label: 'Spots Missing Comma', description: 'Identifies the missing comma after J. Marsh in Entry B', competency: 'AP', positive: true },
      { indicator: 'methodical_comparison', label: 'Methodical Comparison', description: 'Describes checking character-by-character or segment-by-segment', competency: 'PS', positive: true },
      { indicator: 'confirms_no_other_differences', label: 'Confirms No Other Differences', description: 'States confidently there are no other differences', competency: 'AP', positive: true },
    ],
    repeatProtection: false,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PREC-004',
    family: 'Attention & Precision',
    familyCode: '05',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['SO', 'WM'],
    careerContext: ['ame', 'amt', 'assembler'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "Before a maintenance task, a technician's tool inventory contained: 2 screwdrivers, 1 torque wrench, 3 open-end wrenches, 1 inspection mirror, 1 flashlight, and 1 parts tray. After the task, the inventory shows: 2 screwdrivers, 1 torque wrench, 2 open-end wrenches, 1 inspection mirror, 1 flashlight, and 1 parts tray. Is anything different? What would you do?",
    evidenceRubric: [
      { indicator: 'detects_discrepancy', label: 'Detects Discrepancy', description: 'Notices one open-end wrench is missing', competency: 'AP', positive: true },
      { indicator: 'tool_control_response', label: 'Tool Control Response', description: 'Initiates a tool search before clearing the aircraft', competency: 'SO', positive: true },
      { indicator: 'documentation', label: 'Documentation', description: 'Mentions documenting or reporting the discrepancy', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PREC-005',
    family: 'Attention & Precision',
    familyCode: '05',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['SO'],
    careerContext: ['ame', 'amt', 'assembler', 'avionics'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are completing a sign-off on a maintenance task and notice that the work order references part number [PART_A], but the physical part you installed carries part number [PART_B]. What do you do?",
    variantVariables: {
      PART_A: V.partNumber,
      PART_B: ['A35-1178-40', 'B77-2291-71', 'C14-0034-88R', 'D22-5571-30'],
    },
    evidenceRubric: [
      { indicator: 'does_not_sign_off', label: 'Does Not Sign Off', description: 'Does not complete the sign-off with a part number discrepancy unresolved', competency: 'SO', positive: true },
      { indicator: 'verifies_acceptability', label: 'Verifies Acceptability', description: 'Checks whether the installed part is an approved alternate', competency: 'PR', positive: true },
      { indicator: 'corrects_or_escalates', label: 'Corrects or Escalates', description: 'Either corrects the work order or escalates to an authority', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PREC-006',
    family: 'Attention & Precision',
    familyCode: '05',
    primaryCompetency: 'AP',
    secondaryCompetencies: ['WM', 'PR'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "A maintenance procedure requires the following steps in order: 1. Verify aircraft power off. 2. Install safety pin. 3. Disconnect hydraulic line. 4. Verify fluid contained. 5. Remove component.\n\nWhich of the following sequences matches this procedure exactly?\nA) 1, 2, 4, 3, 5\nB) 1, 2, 3, 4, 5\nC) 2, 1, 3, 4, 5\nD) 1, 3, 2, 4, 5",
    evidenceRubric: [
      { indicator: 'correct_sequence', label: 'Correct Sequence', description: 'Selects B — the exact matching sequence', competency: 'AP', positive: true },
      { indicator: 'procedural_accuracy', label: 'Procedural Accuracy', description: 'Values exact sequence adherence', competency: 'PR', positive: true },
    ],
    repeatProtection: false,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 06: Safety Intelligence ──────────────────────────────────────────
  {
    questionId: 'SAFE-001',
    family: 'Safety Intelligence',
    familyCode: '06',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['DM', 'CM', 'PR'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "The [AIRCRAFT] is behind schedule. During your pre-departure check, you notice something on the aircraft that does not match the maintenance documentation. An experienced colleague says, 'It's probably fine — we need to get this aircraft out.' What do you do?",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'hazard_recognition', label: 'Hazard Recognition', description: 'Recognizes the undocumented discrepancy may matter', competency: 'SO', positive: true },
      { indicator: 'pause_containment', label: 'Pause and Contain', description: 'Does not blindly continue the operation', competency: 'SO', positive: true },
      { indicator: 'verification', label: 'Seeks Verification', description: 'Seeks authoritative information or technical data', competency: 'PR', positive: true },
      { indicator: 'escalation', label: 'Escalates Appropriately', description: 'Involves the appropriate person — supervisor, AME, or captain', competency: 'DM', positive: true },
      { indicator: 'pressure_resistance', label: 'Pressure Resistance', description: 'Does not allow schedule pressure to override safety', competency: 'SO', positive: true },
      { indicator: 'communicates_concern', label: 'Communicates Concern', description: 'Clearly communicates the concern to the colleague', competency: 'CM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SAFE-002',
    family: 'Safety Intelligence',
    familyCode: '06',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['DM', 'AL'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "During aircraft preparation, you encounter a condition you've never seen before. Nothing obviously appears damaged. What do you do next?",
    evidenceRubric: [
      { indicator: 'knowledge_limits', label: 'Recognizes Knowledge Limits', description: 'Does not assume unfamiliar = acceptable', competency: 'SO', positive: true },
      { indicator: 'verify_before_proceed', label: 'Verify Before Proceeding', description: 'Seeks verification from an appropriate authority', competency: 'SO', positive: true },
      { indicator: 'documents_observation', label: 'Documents Observation', description: 'Mentions recording or reporting the finding', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SAFE-003',
    family: 'Safety Intelligence',
    familyCode: '06',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['AP', 'PR'],
    careerContext: ['ame', 'amt', 'assembler'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "After completing work on a [AIRCRAFT], you cannot account for one tool from your kit and departure is approaching. What would you do?",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'stops_departure', label: 'Stops Departure', description: 'Does not clear the aircraft with a missing tool', competency: 'SO', positive: true },
      { indicator: 'initiates_search', label: 'Initiates Search', description: 'Conducts systematic tool search', competency: 'AP', positive: true },
      { indicator: 'escalation', label: 'Escalates', description: 'Reports the situation to supervisor or crew', competency: 'CM', positive: true },
      { indicator: 'documentation', label: 'Documentation', description: 'Documents the situation appropriately', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SAFE-004',
    family: 'Safety Intelligence',
    familyCode: '06',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['PR', 'WM'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You're halfway through a safety-critical maintenance task when you're called away urgently. When you return 25 minutes later, what do you do before continuing?",
    evidenceRubric: [
      { indicator: 'does_not_assume_context', label: 'Does Not Assume Context', description: 'Does not resume from memory of where they left off', competency: 'SO', positive: true },
      { indicator: 're_establishes_context', label: 'Re-establishes Context', description: 'Reviews documentation/work order to re-establish position in task', competency: 'PR', positive: true },
      { indicator: 'verifies_work_state', label: 'Verifies Work State', description: 'Confirms what has and has not been completed', competency: 'AP', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'SAFE-005',
    family: 'Safety Intelligence',
    familyCode: '06',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['CM', 'PR', 'DM'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A senior team member instructs you to perform a task differently from what the approved maintenance procedure requires. How would you handle the situation?",
    evidenceRubric: [
      { indicator: 'procedure_authority', label: 'Procedure Authority', description: 'Recognizes the approved procedure takes precedence over verbal instruction', competency: 'PR', positive: true },
      { indicator: 'respectful_challenge', label: 'Respectful Challenge', description: 'Raises the concern professionally without dismissing the senior member', competency: 'CM', positive: true },
      { indicator: 'escalates_if_needed', label: 'Escalates If Needed', description: 'Would escalate to a higher authority if concern is dismissed', competency: 'DM', positive: true },
      { indicator: 'does_not_blindly_comply', label: 'Does Not Blindly Comply', description: 'Does not simply follow authority without question when safety is at stake', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 07: Mission Readiness ─────────────────────────────────────────────
  {
    questionId: 'READY-001',
    family: 'Mission Readiness',
    familyCode: '07',
    primaryCompetency: 'SA',
    secondaryCompetencies: ['SO', 'DM', 'PR'],
    careerContext: ['pilot', 'first_officer', 'ame', 'airport_ops', 'ground_ops'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "Aircraft: [AIRCRAFT]. Crew: available. Fuel: sufficient. Weather: acceptable. Maintenance: one open item under investigation. Documentation: complete. Departure: 35 minutes. Is this aircraft ready for its assigned mission? Explain your reasoning.",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'open_item_concern', label: 'Open Item Concern', description: 'Does not declare ready with an unresolved maintenance item', competency: 'SO', positive: true },
      { indicator: 'investigates_item', label: 'Investigates Item', description: 'Asks what the open item is before deciding', competency: 'SA', positive: true },
      { indicator: 'structured_reasoning', label: 'Structured Reasoning', description: 'Works through each readiness category systematically', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'READY-002',
    family: 'Mission Readiness',
    familyCode: '07',
    primaryCompetency: 'SA',
    secondaryCompetencies: ['DM', 'CM'],
    careerContext: ['pilot', 'first_officer', 'airport_ops', 'ground_ops', 'atc', 'fss'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are about to begin a shift and receive a verbal handover from the outgoing team. The handover is brief and missing details you would normally expect. What specific information would you ask for before accepting the handover, and why?",
    evidenceRubric: [
      { indicator: 'identifies_gaps', label: 'Identifies Gaps', description: 'Asks for outstanding issues, open items, or unresolved situations', competency: 'SA', positive: true },
      { indicator: 'does_not_just_accept', label: 'Does Not Just Accept', description: 'Does not accept an incomplete handover without asking for the missing detail', competency: 'SO', positive: true },
      { indicator: 'structured_questions', label: 'Structured Questions', description: 'Asks specific, organized questions rather than vague ones', competency: 'CM', positive: true },
      { indicator: 'confirms_understanding', label: 'Confirms Understanding', description: 'Reads back or summarizes key points to confirm', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'READY-003',
    family: 'Mission Readiness',
    familyCode: '07',
    primaryCompetency: 'PR',
    secondaryCompetencies: ['SO', 'MT'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "Your pre-task checklist has 12 items. You complete items 1 through 8 and are then interrupted for 10 minutes by an urgent request. When you return, a colleague says they completed items 9 and 10 while you were away, but they used a different version of the checklist. How do you proceed?",
    evidenceRubric: [
      { indicator: 'verifies_version_match', label: 'Verifies Version Match', description: 'Confirms the colleague used the same approved version before accepting their work', competency: 'PR', positive: true },
      { indicator: 'does_not_assume_equivalent', label: 'Does Not Assume Equivalent', description: 'Does not assume a different version covers the same items', competency: 'SO', positive: true },
      { indicator: 'confirms_items_9_10', label: 'Confirms Items 9 and 10', description: 'Re-verifies or independently confirms the disputed items if versions differ', competency: 'AP', positive: true },
      { indicator: 'completes_remaining', label: 'Completes Remaining Items', description: 'Returns to item 11 and continues from the confirmed point', competency: 'MT', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'READY-004',
    family: 'Mission Readiness',
    familyCode: '07',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['SO', 'DM', 'SA'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You made an initial readiness decision for a flight. New information has just arrived reporting a maintenance discrepancy that was not known earlier. How do you reassess, and does your original decision stand?",
    evidenceRubric: [
      { indicator: 'updates_decision', label: 'Updates Decision', description: 'Appropriately revises the decision based on new evidence', competency: 'AL', positive: true },
      { indicator: 'no_ego_defense', label: 'No Ego Defense', description: 'Does not defend original decision simply to avoid being wrong', competency: 'DM', positive: true },
      { indicator: 'investigates_discrepancy', label: 'Investigates Discrepancy', description: 'Asks for details about the discrepancy before deciding', competency: 'SA', positive: true },
    ],
    designNote: "Changing a decision appropriately when evidence changes is positive evidence for AL and DM.",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 08: Working Memory ────────────────────────────────────────────────
  {
    questionId: 'MEM-001',
    family: 'Working Memory',
    familyCode: '08',
    primaryCompetency: 'WM',
    secondaryCompetencies: [],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'memory_recall',
    priorKnowledgeRequired: false,
    questionTemplate: "BRIEFING — review this information:\n\nAircraft: [AIRCRAFT]\nAssigned [GATE]\nDeparture: [TIME]\n[RUNWAY]\nWeather: [WEATHER]\nCrew: 12 aboard\n\n[After completing a short task below, you will be asked to recall specific details.]\n\nIntermediate task: What is the first thing a maintenance technician should verify after arriving at an unfamiliar aircraft?\n\nNow, from the briefing above — which gate was assigned?",
    variantVariables: {
      AIRCRAFT: V.aircraft,
      GATE: V.gate,
      TIME: V.time,
      RUNWAY: V.runway,
      WEATHER: V.weather,
    },
    evidenceRubric: [
      { indicator: 'recalls_gate', label: 'Recalls Gate', description: 'Correctly recalls the assigned gate', competency: 'WM', positive: true },
      { indicator: 'intermediate_task_quality', label: 'Intermediate Task Quality', description: 'Also gives a reasonable answer to the maintenance question', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MEM-002',
    family: 'Working Memory',
    familyCode: '08',
    primaryCompetency: 'WM',
    secondaryCompetencies: ['MT'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'memory_recall',
    priorKnowledgeRequired: false,
    questionTemplate: "OPERATIONAL BRIEFING:\n\nAircraft: [AIRCRAFT]\nFlight number: [FLIGHT]\nDeparture gate: [GATE]\nDeparture time: [TIME]\nPassenger count: 142\nFuel state: within limits\nWeather: [WEATHER]\n\n[Intermediate task: A pilot notices an unusual vibration in the rudder pedals during taxi. What would be your first response?]\n\nFrom the briefing — what was the passenger count and what was the weather?",
    variantVariables: {
      AIRCRAFT: V.aircraft,
      FLIGHT: ['AC 441', 'WJ 819', 'TS 206', 'PD 334'],
      GATE: V.gate,
      TIME: V.time,
      WEATHER: V.weather,
    },
    evidenceRubric: [
      { indicator: 'recalls_passenger_count', label: 'Recalls Passenger Count', description: 'Correctly recalls 142 passengers', competency: 'WM', positive: true },
      { indicator: 'recalls_weather', label: 'Recalls Weather', description: 'Correctly recalls the weather condition from the briefing', competency: 'WM', positive: true },
      { indicator: 'intermediate_task_reasonable', label: 'Intermediate Task Reasonable', description: 'Gives a reasonable response to the vibration question', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MEM-003',
    family: 'Working Memory',
    familyCode: '08',
    primaryCompetency: 'WM',
    secondaryCompetencies: ['PS', 'SA'],
    careerContext: ['atc', 'fss', 'airport_ops', 'pilot', 'first_officer'],
    difficulty: 3,
    interactionType: 'memory_recall',
    priorKnowledgeRequired: false,
    questionTemplate: "TRAFFIC PICTURE:\nAircraft 1: [AIRCRAFT] at [GATE], holding for pushback, crew ready.\nAircraft 2: Dash 8, taxiing from Bay 3 to [RUNWAY], ETD [TIME].\nAircraft 3: [AIRCRAFT2] inbound, 12 minutes out, requesting gate assignment.\nGroundside: fuel truck en route to [GATE2].\n\n[Intermediate task: What is the most common cause of runway incursions during night operations?]\n\nFinal question: Which aircraft is inbound, and how many minutes out is it?",
    variantVariables: {
      AIRCRAFT: V.aircraft,
      AIRCRAFT2: ['Boeing 737', 'Airbus A320', 'Embraer 175'],
      GATE: V.gate,
      GATE2: ['Gate 7', 'Gate 18', 'Gate 33'],
      RUNWAY: V.runway,
      TIME: V.time,
    },
    evidenceRubric: [
      { indicator: 'recalls_inbound_aircraft', label: 'Recalls Inbound Aircraft', description: 'Correctly identifies the inbound aircraft type', competency: 'WM', positive: true },
      { indicator: 'recalls_12_minutes', label: 'Recalls 12 Minutes', description: 'Recalls the 12-minute ETA without reverting to another detail', competency: 'SA', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MEM-004',
    family: 'Working Memory',
    familyCode: '08',
    primaryCompetency: 'WM',
    secondaryCompetencies: ['AL'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'memory_recall',
    priorKnowledgeRequired: false,
    questionTemplate: "OPERATIONAL UPDATE:\nInitial assignment: Gate 18.\n\n[Intermediate task: An aircraft lands with a reported navigation system fault. What is the first thing you would do upon receiving this report?]\n\nUPDATE: Gate has been changed to Gate 21.\n\n[After a final short task: List two key things a pre-departure safety check should always include.]\n\nFinal question: Which gate should the crew now report to?",
    evidenceRubric: [
      { indicator: 'recalls_updated_gate', label: 'Recalls Updated Gate', description: 'Correctly recalls Gate 21 (the update, not the original)', competency: 'WM', positive: true },
      { indicator: 'not_original', label: 'Uses Current Information', description: 'Does not revert to original Gate 18', competency: 'AL', positive: true },
    ],
    designNote: "Measures working memory updating, not just recall.",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 09: Prioritization & Multitasking ────────────────────────────────
  {
    questionId: 'MULTI-001',
    family: 'Prioritization & Multitasking',
    familyCode: '09',
    primaryCompetency: 'MT',
    secondaryCompetencies: ['SO', 'DM', 'SA'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are handling a routine maintenance task when the following all occur nearly simultaneously: a safety warning light activates on a nearby aircraft, a radio message arrives with an ATC instruction, a colleague asks a routine scheduling question, the work schedule changes for the afternoon, and a passenger requests assistance nearby. Walk through your priorities and explain your reasoning.",
    evidenceRubric: [
      { indicator: 'safety_first', label: 'Safety First', description: 'Safety warning is treated with highest priority', competency: 'SO', positive: true },
      { indicator: 'structured_triage', label: 'Structured Triage', description: 'Prioritizes items in a logical, defensible order', competency: 'MT', positive: true },
      { indicator: 'preserves_secondary', label: 'Preserves Secondary Items', description: 'Acknowledges lower-priority items without losing them', competency: 'WM', positive: true },
      { indicator: 'context_awareness', label: 'Context Awareness', description: 'Considers the operational context in prioritization', competency: 'SA', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MULTI-002',
    family: 'Prioritization & Multitasking',
    familyCode: '09',
    primaryCompetency: 'MT',
    secondaryCompetencies: ['WM', 'CM'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are in the middle of writing a maintenance report when three things happen at once: a colleague asks for the serial number of a component you were just working on, your radio crackles with a routine status update request, and a reminder appears that a time-sensitive parts order closes in 15 minutes. Describe how you handle the next five minutes.",
    evidenceRubric: [
      { indicator: 'addresses_time_critical_first', label: 'Addresses Time-Critical First', description: 'Prioritizes the parts order closing in 15 minutes', competency: 'MT', positive: true },
      { indicator: 'queues_other_items', label: 'Queues Other Items', description: 'Briefly acknowledges or defers the radio and colleague without losing track', competency: 'WM', positive: true },
      { indicator: 'communicates_delay', label: 'Communicates Delay', description: 'Tells the colleague or radio contact they will respond shortly', competency: 'CM', positive: true },
      { indicator: 'returns_to_report', label: 'Returns to Report', description: 'Plans to return to the maintenance report after handling priorities', competency: 'MT', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'MULTI-003',
    family: 'Prioritization & Multitasking',
    familyCode: '09',
    primaryCompetency: 'MT',
    secondaryCompetencies: ['SO', 'DM'],
    careerContext: ['ame', 'amt', 'assembler', 'airport_ops', 'ground_ops'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You're in the hangar and the following compete for your attention: an active maintenance task you are halfway through, a missing component for a different work package, a message from your supervisor asking for a status update, an incoming aircraft that needs to be marshalled, and a documentation deadline in 30 minutes. Prioritize these and explain why.",
    evidenceRubric: [
      { indicator: 'safety_critical_first', label: 'Safety-Critical First', description: 'Addresses the active task or incoming aircraft first (safety)', competency: 'SO', positive: true },
      { indicator: 'logical_priority_order', label: 'Logical Order', description: 'Provides a defensible priority ranking with reasoning', competency: 'MT', positive: true },
      { indicator: 'communication_loop', label: 'Communication Loop', description: 'Notes they would communicate status/delays to supervisor', competency: 'CM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 10: Communication Intelligence ───────────────────────────────────
  {
    questionId: 'COMM-001',
    family: 'Communication Intelligence',
    familyCode: '10',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['AL'],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "Think of a time when you had to explain something technical or complex to someone who was unfamiliar with the topic. How did you approach it, and how did you know the other person understood?",
    evidenceRubric: [
      { indicator: 'adapts_to_audience', label: 'Adapts to Audience', description: 'Adjusts language or approach based on the listener\'s level', competency: 'CM', positive: true },
      { indicator: 'checks_understanding', label: 'Checks Understanding', description: 'Describes how they confirmed comprehension', competency: 'CM', positive: true },
      { indicator: 'uses_analogy_or_example', label: 'Uses Analogy or Example', description: 'Uses a concrete example or analogy to bridge the knowledge gap', competency: 'AL', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'COMM-002',
    family: 'Communication Intelligence',
    familyCode: '10',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['SO', 'DM'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You believe something on an aircraft may be unsafe, but you're not certain — it could just be unfamiliar to you. How would you raise this concern with your supervisor?",
    evidenceRubric: [
      { indicator: 'raises_concern', label: 'Raises the Concern', description: 'Speaks up despite uncertainty', competency: 'SO', positive: true },
      { indicator: 'acknowledges_uncertainty', label: 'Acknowledges Uncertainty', description: 'Is honest about what they do and do not know', competency: 'CM', positive: true },
      { indicator: 'specific_description', label: 'Specific Description', description: 'Describes the observation clearly and specifically', competency: 'CM', positive: true },
      { indicator: 'does_not_self_censor', label: 'Does Not Self-Censor', description: 'Does not stay silent to avoid looking uninformed', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'COMM-003',
    family: 'Communication Intelligence',
    familyCode: '10',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['SO', 'PR'],
    careerContext: 'all',
    difficulty: 1,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A team member gives you an instruction that you do not fully understand. What would you say or do?",
    evidenceRubric: [
      { indicator: 'seeks_clarification', label: 'Seeks Clarification', description: 'Asks for clarification rather than proceeding on assumption', competency: 'CM', positive: true },
      { indicator: 'does_not_pretend', label: 'Does Not Pretend', description: 'Does not pretend to understand when they do not', competency: 'SO', positive: true },
      { indicator: 'specific_question', label: 'Asks a Specific Question', description: 'Identifies specifically what needs clarification', competency: 'CM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'COMM-004',
    family: 'Communication Intelligence',
    familyCode: '10',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['SA', 'DM'],
    careerContext: ['pilot', 'first_officer', 'atc', 'fss', 'airport_ops', 'ground_ops'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You transmit an instruction to a colleague over the radio. They read back a different instruction than what you said. What do you do next, and why does the readback matter?",
    evidenceRubric: [
      { indicator: 'corrects_immediately', label: 'Corrects Immediately', description: 'Immediately corrects the misread-back instruction before action is taken', competency: 'CM', positive: true },
      { indicator: 'explains_readback_purpose', label: 'Explains Readback Purpose', description: 'Articulates that readback exists to catch exactly this kind of error', competency: 'SA', positive: true },
      { indicator: 'does_not_assume_correct', label: 'Does Not Assume Correct', description: 'Does not assume the colleague will self-correct — actively intervenes', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'COMM-005',
    family: 'Communication Intelligence',
    familyCode: '10',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['AP', 'SA'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You have just received the following operational briefing and need to pass the essential information to the next team member:\n\n'Aircraft C-GABC has completed its maintenance check. The hydraulics show within limits. There is a minor snag on the APU that has been deferred with reference to MEL Item 22-B. Fuel was uplifted to 18,500 lbs. All navigation and communication systems are serviceable. One open cabin item — a broken tray table in seat 14C — is noted in the cabin log. Pushback is scheduled for 16:40. Crew has been briefed.'\n\nWhat would you tell the next team member?",
    evidenceRubric: [
      { indicator: 'critical_info_retained', label: 'Critical Information Retained', description: 'Includes hydraulics, MEL deferral, fuel load, and departure time', competency: 'CM', positive: true },
      { indicator: 'concise_transfer', label: 'Concise Transfer', description: 'Does not simply repeat everything verbatim — filters to essential', competency: 'AP', positive: true },
      { indicator: 'open_items_flagged', label: 'Open Items Flagged', description: 'Highlights the MEL deferral as the key open item', competency: 'SA', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 11: Regulatory & Procedural Intelligence ─────────────────────────
  {
    questionId: 'REG-001',
    family: 'Regulatory & Procedural Intelligence',
    familyCode: '11',
    primaryCompetency: 'PR',
    secondaryCompetencies: ['SO', 'AL'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You discover that a maintenance activity you need to perform is governed by a regulation you have not encountered before. What would you do before proceeding with the work?",
    evidenceRubric: [
      { indicator: 'researches_regulation', label: 'Researches Regulation', description: 'Seeks out the relevant regulatory requirement before proceeding', competency: 'PR', positive: true },
      { indicator: 'does_not_guess', label: 'Does Not Guess', description: 'Does not assume what the regulation requires', competency: 'SO', positive: true },
      { indicator: 'appropriate_source', label: 'Appropriate Source', description: 'Identifies an authoritative source (regulator, approved documents)', competency: 'AL', positive: true },
      { indicator: 'seeks_guidance', label: 'Seeks Guidance', description: 'Consults a supervisor or technical authority if needed', competency: 'CM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'REG-002',
    family: 'Regulatory & Procedural Intelligence',
    familyCode: '11',
    primaryCompetency: 'PR',
    secondaryCompetencies: ['DM', 'SO'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A maintenance procedure specifies six mandatory inspections after a component is installed. Due to time pressure, a colleague suggests skipping inspection number four because, in their experience, it rarely catches anything. How would you respond?",
    evidenceRubric: [
      { indicator: 'does_not_skip', label: 'Does Not Skip', description: 'Declines to skip the mandatory inspection step', competency: 'PR', positive: true },
      { indicator: 'references_procedure_authority', label: 'References Procedure Authority', description: 'States the procedure is mandatory regardless of historical experience', competency: 'SO', positive: true },
      { indicator: 'professional_pushback', label: 'Professional Pushback', description: 'Responds to the colleague professionally, not dismissively', competency: 'CM', positive: true },
      { indicator: 'escalates_if_pressure_continues', label: 'Escalates If Pressure Continues', description: 'Would involve a supervisor if the colleague continues to push', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'REG-003',
    family: 'Regulatory & Procedural Intelligence',
    familyCode: '11',
    primaryCompetency: 'PR',
    secondaryCompetencies: ['AL', 'PS'],
    careerContext: ['ame', 'amt', 'avionics'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A new airworthiness directive (AD) has been issued that affects an aircraft you are responsible for. You have never dealt with this type of AD before. Walk through how you would determine what action is required and by when.",
    evidenceRubric: [
      { indicator: 'reads_full_ad', label: 'Reads Full AD', description: 'Reviews the complete AD text, not just the summary', competency: 'PR', positive: true },
      { indicator: 'identifies_applicability', label: 'Identifies Applicability', description: 'Checks whether the specific aircraft serial or model falls under the AD', competency: 'AP', positive: true },
      { indicator: 'determines_compliance_time', label: 'Determines Compliance Time', description: 'Identifies the compliance deadline or flight-hour threshold', competency: 'PS', positive: true },
      { indicator: 'seeks_guidance_if_unclear', label: 'Seeks Guidance If Unclear', description: 'Consults engineering, technical authority, or the regulator if interpretation is uncertain', competency: 'AL', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'REG-004',
    family: 'Regulatory & Procedural Intelligence',
    familyCode: '11',
    primaryCompetency: 'PR',
    secondaryCompetencies: ['SO', 'AP'],
    careerContext: ['ame', 'amt'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You have two copies of the same maintenance procedure in front of you. One is dated six months ago and one is dated two weeks ago. Which one would you use, and how would you confirm it is the correct one to follow?",
    evidenceRubric: [
      { indicator: 'verifies_current_controlled', label: 'Verifies Current Controlled', description: 'Does not rely only on the date — verifies which is the current approved/controlled document', competency: 'PR', positive: true },
      { indicator: 'queries_revision', label: 'Queries Revision Status', description: 'Checks revision numbers, control stamps, or the manual index', competency: 'AP', positive: true },
      { indicator: 'not_just_date', label: 'Not Just Date', description: 'Recognizes newer date does not automatically mean current approved revision', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 12: Pilot Pathway Intelligence ───────────────────────────────────
  {
    questionId: 'PILOT-001',
    family: 'Pilot Pathway Intelligence',
    familyCode: '12',
    primaryCompetency: 'DM',
    secondaryCompetencies: ['AL'],
    careerContext: ['pilot', 'first_officer'],
    difficulty: 2,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "You want to become a professional pilot but currently have no flight experience. Before choosing a training pathway, what would you want to understand first?",
    evidenceRubric: [
      { indicator: 'considers_pathway_factors', label: 'Considers Pathway Factors', description: 'Identifies licensing requirements, cost, timeline, or career goals', competency: 'DM', positive: true },
      { indicator: 'researches_before_committing', label: 'Researches Before Committing', description: 'Plans to gather information before choosing', competency: 'AL', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PILOT-002',
    family: 'Pilot Pathway Intelligence',
    familyCode: '12',
    primaryCompetency: 'SA',
    secondaryCompetencies: ['DM', 'SO'],
    careerContext: ['pilot', 'first_officer'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are flying en route and notice the weather at your destination is deteriorating faster than forecast. You still have legal fuel to continue but your alternate is also showing reduced visibility. What factors would you consider in deciding whether to continue or divert?",
    evidenceRubric: [
      { indicator: 'considers_fuel_state', label: 'Considers Fuel State', description: 'Evaluates fuel against all scenarios including divert', competency: 'SA', positive: true },
      { indicator: 'proactive_not_reactive', label: 'Proactive Not Reactive', description: 'Makes the divert decision early, not at the last possible moment', competency: 'DM', positive: true },
      { indicator: 'considers_alternate', label: 'Considers the Alternate', description: 'Checks alternate weather and fuel required to reach it', competency: 'PS', positive: true },
      { indicator: 'safety_over_schedule', label: 'Safety Over Schedule', description: 'Does not allow schedule or passenger pressure to override safety margins', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PILOT-003',
    family: 'Pilot Pathway Intelligence',
    familyCode: '12',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['MT', 'PR'],
    careerContext: ['pilot', 'first_officer'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "During a busy approach phase, your First Officer reads back an ATC clearance that contains an altitude that differs from what ATC actually said. You are currently hand-flying the aircraft and managing high workload. What do you do?",
    evidenceRubric: [
      { indicator: 'corrects_readback', label: 'Corrects the Readback', description: 'Immediately challenges the incorrect readback before it is acknowledged to ATC', competency: 'CM', positive: true },
      { indicator: 'manages_workload', label: 'Manages Workload', description: 'Handles the correction without compromising aircraft control', competency: 'MT', positive: true },
      { indicator: 'confirms_correct_clearance', label: 'Confirms Correct Clearance', description: 'Ensures the crew has the correct altitude before proceeding', competency: 'PR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'PILOT-004',
    family: 'Pilot Pathway Intelligence',
    familyCode: '12',
    primaryCompetency: 'DM',
    secondaryCompetencies: ['CM', 'SO', 'SA'],
    careerContext: ['pilot', 'first_officer'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A pilot wants to progress from First Officer toward command responsibility. Beyond accumulating flight time, what capabilities do you think become increasingly important for that progression?",
    evidenceRubric: [
      { indicator: 'leadership_mentioned', label: 'Leadership Mentioned', description: 'References leadership, crew management, or decision authority', competency: 'DM', positive: true },
      { indicator: 'judgment_depth', label: 'Judgment and Depth', description: 'Goes beyond technical skills to judgment, CRM, situational awareness', competency: 'SA', positive: true },
      { indicator: 'communication_culture', label: 'Communication / Culture', description: 'References crew communication, safety culture, or operational standards', competency: 'CM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 13: AME / AMT Intelligence ───────────────────────────────────────
  {
    questionId: 'AME-001',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'AL',
    secondaryCompetencies: [],
    careerContext: ['ame', 'amt'],
    difficulty: 1,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "What interests you about working directly with aircraft systems and components?",
    evidenceRubric: [
      { indicator: 'specific_interest', label: 'Specific Interest', description: 'Names a specific aspect of aircraft systems or maintenance', competency: 'AL', positive: true },
      { indicator: 'practical_orientation', label: 'Practical Orientation', description: 'Shows interest in hands-on or diagnostic work', competency: 'MR', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'AME-002',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'PS',
    secondaryCompetencies: ['MR', 'PR'],
    careerContext: ['ame', 'amt', 'avionics'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "A component on a [AIRCRAFT] is not operating as expected. You have three possible causes but insufficient evidence to determine which one is responsible. What do you do next?",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'systematic_elimination', label: 'Systematic Elimination', description: 'Plans a methodical approach to isolate the cause', competency: 'PS', positive: true },
      { indicator: 'evidence_first', label: 'Evidence First', description: 'Gathers more evidence before acting on an assumption', competency: 'MR', positive: true },
      { indicator: 'documents_approach', label: 'Documents Approach', description: 'Mentions documentation of findings at each step', competency: 'PR', positive: true },
      { indicator: 'does_not_guess', label: 'Does Not Guess', description: 'Does not act on the most likely cause without elimination', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'AME-003',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'PS',
    secondaryCompetencies: ['AP', 'SA'],
    careerContext: ['ame', 'amt'],
    difficulty: 4,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "The same fault on a [AIRCRAFT] has been reported three times. Each time, the previous action appeared to resolve it — but it returns. How would you approach it this time?",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'root_cause_focus', label: 'Root Cause Focus', description: 'Does not repeat previous fixes — looks for underlying cause', competency: 'PS', positive: true },
      { indicator: 'pattern_recognition', label: 'Pattern Recognition', description: 'Looks for patterns across the three occurrences', competency: 'AP', positive: true },
      { indicator: 'engineering_involvement', label: 'Engineering Involvement', description: 'Considers involving engineering or technical authority', competency: 'SA', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'AME-004',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'PR',
    secondaryCompetencies: ['AP', 'SO'],
    careerContext: ['ame', 'amt'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You complete a maintenance task and are preparing to sign off the work order. You realize you did not make an entry at one of the intermediate inspection checkpoints, even though you did perform that inspection. What do you do?",
    evidenceRubric: [
      { indicator: 'does_not_backfill_falsely', label: 'Does Not Backfill Falsely', description: 'Does not simply add a retrospective entry as if it were made at the time', competency: 'PR', positive: true },
      { indicator: 'documents_correction', label: 'Documents Correction', description: 'Makes a corrective entry with the actual current time and a note', competency: 'AP', positive: true },
      { indicator: 'involves_supervisor', label: 'Involves Supervisor', description: 'Brings the omission to a supervisor or QA before signing off', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'AME-005',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'PS',
    secondaryCompetencies: ['AL', 'MR'],
    careerContext: ['ame', 'amt', 'avionics'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "An avionics system on a [AIRCRAFT] shows an intermittent fault — it appears on some flights and not others, and ground testing has not been able to reproduce it. What approach would you take to isolate the cause?",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'collects_data_across_occurrences', label: 'Collects Data Across Occurrences', description: 'Reviews fault history across multiple flights before acting', competency: 'PS', positive: true },
      { indicator: 'considers_environmental_factors', label: 'Considers Environmental Factors', description: 'Looks for patterns related to temperature, vibration, altitude, or phase of flight', competency: 'AL', positive: true },
      { indicator: 'uses_built_in_test_data', label: 'Uses Built-In Test Data', description: 'References BITE data or fault logs from the aircraft systems', competency: 'MR', positive: true },
      { indicator: 'does_not_close_without_cause', label: 'Does Not Close Without Cause', description: 'Does not clear the fault simply because ground test is negative', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'AME-006',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'CM',
    secondaryCompetencies: ['SO', 'PR'],
    careerContext: ['ame', 'amt'],
    difficulty: 2,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You are handing over an incomplete maintenance task to the night shift. The task is 70% done, and there is one known issue you haven't resolved yet. How do you structure the handover to ensure continuity and safety?",
    evidenceRubric: [
      { indicator: 'states_completion_point', label: 'States Completion Point', description: 'Clearly identifies exactly where in the task they stopped', competency: 'CM', positive: true },
      { indicator: 'flags_unresolved_issue', label: 'Flags Unresolved Issue', description: 'Explicitly calls out the known unresolved issue', competency: 'SO', positive: true },
      { indicator: 'references_documentation', label: 'References Documentation', description: 'Directs the incoming technician to the work order and any open entries', competency: 'PR', positive: true },
      { indicator: 'confirms_understanding', label: 'Confirms Understanding', description: 'Ensures the incoming technician has understood the handover', competency: 'CM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'AME-007',
    family: 'AME / AMT Intelligence',
    familyCode: '13',
    primaryCompetency: 'SO',
    secondaryCompetencies: ['PR', 'DM'],
    careerContext: ['ame', 'amt'],
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "During a task on a [AIRCRAFT], you notice the physical component in front of you does not match the drawing you are working from. Which do you trust — the component or the drawing — and what do you do?",
    variantVariables: { AIRCRAFT: V.aircraft },
    evidenceRubric: [
      { indicator: 'neither_blindly', label: 'Trusts Neither Blindly', description: 'Stops and verifies rather than defaulting to either source', competency: 'SO', positive: true },
      { indicator: 'controlled_technical_data', label: 'Controlled Technical Data', description: 'Seeks the current, controlled technical data source', competency: 'PR', positive: true },
      { indicator: 'escalation', label: 'Escalates to Authority', description: 'Involves engineering or technical authority', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 14: Adaptive Learning ────────────────────────────────────────────
  {
    questionId: 'ADAPT-001',
    family: 'Adaptive Learning',
    familyCode: '14',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['PS'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Here is a reasoning challenge:\n\nA system has three components in sequence: A, B, and C. A is the input, B transforms the input, and C produces the output. If B's transformation rate doubles, what happens to the output at C — and why?\n\n[If you're not sure, take your best guess and explain your thinking.]",
    evidenceRubric: [
      { indicator: 'attempts_reasoning', label: 'Attempts Reasoning', description: 'Makes an attempt to reason through the problem', competency: 'PS', positive: true },
      { indicator: 'cause_effect_chain', label: 'Cause-Effect Chain', description: 'Traces the effect through A → B → C', competency: 'MR', positive: true },
      { indicator: 'acknowledges_uncertainty', label: 'Acknowledges Uncertainty', description: 'Honest about what they are not sure of', competency: 'AL', positive: true },
    ],
    adaptiveFollowUp: "ADAPT-002",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'ADAPT-002',
    family: 'Adaptive Learning',
    familyCode: '14',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['MR', 'PS'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response',
    priorKnowledgeRequired: false,
    questionTemplate: "Building on that: in a hydraulic system, if the pump (the input) runs at double its normal flow rate but all output pressure regulators remain unchanged, what do you think happens to the system pressure — and what concern might that raise?",
    evidenceRubric: [
      { indicator: 'transfers_learning', label: 'Transfers Learning', description: 'Applies the principle from ADAPT-001 to a new system', competency: 'AL', positive: true },
      { indicator: 'identifies_consequence', label: 'Identifies Consequence', description: 'Identifies a potential pressure or overload consequence', competency: 'MR', positive: true },
      { indicator: 'safety_implication', label: 'Safety Implication', description: 'Notes a safety concern (overpressure, component stress)', competency: 'SO', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'ADAPT-003',
    family: 'Adaptive Learning',
    familyCode: '14',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['DM', 'SA'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You made a decision earlier in this assessment. You've now been given new information showing that one of your initial assumptions was incorrect. Looking back at that decision — would you change it now that you have this information, and what does that tell you about how you approach decisions?",
    evidenceRubric: [
      { indicator: 'willing_to_revise', label: 'Willing to Revise', description: 'Revisits and updates the decision based on new evidence', competency: 'AL', positive: true },
      { indicator: 'explains_change', label: 'Explains the Change', description: 'Articulates what changed and why', competency: 'DM', positive: true },
      { indicator: 'reflective', label: 'Self-Reflective', description: 'Shows insight into their own decision-making process', competency: 'SA', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },

  // ── BANK 15: Education & Workforce Navigation ─────────────────────────────
  {
    questionId: 'CAREER-001',
    family: 'Education & Workforce Navigation',
    familyCode: '15',
    primaryCompetency: 'DM',
    secondaryCompetencies: ['AL'],
    careerContext: ['ame', 'amt'],
    difficulty: 2,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "You've identified aircraft maintenance as a potential career pathway and are comparing programs at different institutions. What information would you compare before choosing a program?",
    evidenceRubric: [
      { indicator: 'program_factors', label: 'Program Factors', description: 'Considers accreditation, industry placement, length, cost, or location', competency: 'DM', positive: true },
      { indicator: 'regulatory_alignment', label: 'Regulatory Alignment', description: 'Considers whether program leads to Transport Canada licensing', competency: 'AL', positive: true },
    ],
    designNote: "Do not score institution preference. Program facts must be verified before surfacing as factual guidance.",
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'CAREER-002',
    family: 'Education & Workforce Navigation',
    familyCode: '15',
    primaryCompetency: 'DM',
    secondaryCompetencies: ['AL', 'SA'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "You are exploring a career in aviation but are uncertain which specific pathway fits you best. What would you do to narrow down your options before committing to a training program or apprenticeship?",
    evidenceRubric: [
      { indicator: 'gathers_information_first', label: 'Gathers Information First', description: 'Describes researching pathways, speaking with professionals, or job shadowing before deciding', competency: 'AL', positive: true },
      { indicator: 'considers_personal_fit', label: 'Considers Personal Fit', description: 'Reflects on their own strengths, interests, or constraints in the decision', competency: 'SA', positive: true },
      { indicator: 'structured_decision_approach', label: 'Structured Decision Approach', description: 'Proposes a deliberate process rather than a random or impulsive choice', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'CAREER-003',
    family: 'Education & Workforce Navigation',
    familyCode: '15',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['PS', 'DM'],
    careerContext: 'all',
    difficulty: 3,
    interactionType: 'open_response_scenario',
    priorKnowledgeRequired: false,
    questionTemplate: "You have been working in aviation for six months in an entry-level role. You receive feedback that you are technically capable but need to develop stronger communication skills to advance. How would you respond to that feedback, and what would your next steps be?",
    evidenceRubric: [
      { indicator: 'accepts_feedback', label: 'Accepts Feedback', description: 'Receives the feedback constructively, not defensively', competency: 'AL', positive: true },
      { indicator: 'concrete_development_plan', label: 'Concrete Development Plan', description: 'Identifies specific steps to improve communication skills', competency: 'PS', positive: true },
      { indicator: 'seeks_support', label: 'Seeks Support', description: 'Considers mentorship, coaching, or structured feedback to accelerate development', competency: 'DM', positive: true },
      { indicator: 'tracks_progress', label: 'Tracks Progress', description: 'Plans to follow up or measure improvement over time', competency: 'AL', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
  {
    questionId: 'CAREER-004',
    family: 'Education & Workforce Navigation',
    familyCode: '15',
    primaryCompetency: 'AL',
    secondaryCompetencies: ['DM'],
    careerContext: 'all',
    difficulty: 2,
    interactionType: 'discovery',
    priorKnowledgeRequired: false,
    questionTemplate: "An employer says that blueprint reading and power-tool experience would strengthen your application for an aircraft assembly position — skills you don't currently have. What would your next step be?",
    evidenceRubric: [
      { indicator: 'proactive_response', label: 'Proactive Response', description: 'Identifies a concrete step to develop the missing skills', competency: 'AL', positive: true },
      { indicator: 'realistic_plan', label: 'Realistic Plan', description: 'Describes a practical path to gaining those skills', competency: 'DM', positive: true },
    ],
    repeatProtection: true,
    status: 'active',
    version: '1.0',
  },
];

export const QUESTION_FAMILIES = [
  { code: '01', name: 'Aviation Discovery' },
  { code: '02', name: 'Spatial Intelligence' },
  { code: '03', name: 'Mechanical Intelligence' },
  { code: '04', name: 'Blueprint & Technical Intelligence' },
  { code: '05', name: 'Attention & Precision' },
  { code: '06', name: 'Safety Intelligence' },
  { code: '07', name: 'Mission Readiness' },
  { code: '08', name: 'Working Memory' },
  { code: '09', name: 'Prioritization & Multitasking' },
  { code: '10', name: 'Communication Intelligence' },
  { code: '11', name: 'Regulatory & Procedural Intelligence' },
  { code: '12', name: 'Pilot Pathway Intelligence' },
  { code: '13', name: 'AME / AMT Intelligence' },
  { code: '14', name: 'Adaptive Learning' },
  { code: '15', name: 'Education & Workforce Navigation' },
] as const;

export function getQuestionById(id: string): QuestionRecord | undefined {
  return QUESTION_BANK.find(q => q.questionId === id);
}

export function getQuestionsByFamily(code: string): QuestionRecord[] {
  return QUESTION_BANK.filter(q => q.familyCode === code);
}

export function getActiveQuestions(): QuestionRecord[] {
  return QUESTION_BANK.filter(q => q.status === 'active');
}

export function getQuestionsByCompetency(key: CompetencyKey): QuestionRecord[] {
  return QUESTION_BANK.filter(
    q => q.primaryCompetency === key || q.secondaryCompetencies.includes(key)
  );
}

export function getQuestionsForPathway(pathway: PathwayId): QuestionRecord[] {
  return QUESTION_BANK.filter(
    q => q.careerContext === 'all' || (q.careerContext as PathwayId[]).includes(pathway)
  );
}
